name = "warp"
main = "src/index.ts"
compatibility_date = "2023-08-23"

[[d1_databases]]
binding = "DATABASE"
database_name = "warp-db"
database_id = "61ac8570-00b5-4192-bd53-5aadb823c1cd"

[triggers]
crons = [
    '* * * * *', # every minute
]

